project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "*/*.qmd"
    - "*/*/*.qmd"

website:
  site-url: "https://sbhardwaj.com"
  draft-mode: unlinked
  favicon: favicon.svg

format:
  html:
    theme: none
    document-css: false
    css: styles.css
    page-layout: full
    title-block-banner: false
    toc: false
    include-in-header: fonts.html
    include-after-body: anchor-links.html
